name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v4
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
      
      
      - name: Compilar codigo
        run: |
          mvn package
          #echo "package"
      - name: Analisis SonarCloud
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=devOps-lab-final \
            -Dsonar.projectKey=devOps-lab-final_ms-aumento-voto
        
        
